worker_processes 1;
events { worker_connections 1024; }

http {
    server {
        listen 80;
        
        location /chain {
            proxy_set_header X-Forwarded-For "";
            proxy_set_header X-Forwarded-For "$remote_addr, 10.2.0.10";
            proxy_pass http://10.2.0.11/chain;
        }
        
        location /web {
            proxy_set_header X-Forwarded-For "";
            proxy_set_header X-Forwarded-For "$remote_addr, 10.2.0.10";
            proxy_pass http://10.2.0.13:8080;
        }
        
        location / {
            proxy_set_header X-Forwarded-For "";
            proxy_set_header X-Forwarded-For "$remote_addr, 10.2.0.10";
            proxy_pass http://10.2.0.11;
        }
    }
}
